  
version: '3'
services:
#mssql docker
  pharmacy-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - pharmacynet

  fitbody-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:pharmacyPos=Server=pharmacy-sql,1433;Database=IB160048;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 58744:5050
    networks:
      - pharmacynet
    links:
      - pharmacy-sql
    depends_on:
      - pharmacy-sql
      
networks:
  pharmacynet:
    driver: bridge